version: "3.7"
services:
  web-api:
    image: "suza8a/backend"
    depends_on:
      - mongo
    ports:
      - 6001:80
  mongo:
    image: "mongo"
  web:
    image: "suza8a/frontend"
  nginx:
    image: "nginx"
    depends_on:
      - web
      - web-api
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
